name = "abhi"
print(len(name))
print(name.find("a"))
print(name.capitalize())
print(name.upper())
print(name.lower())
print(name.isdigit()) 
print(name.isalpha())
print(name.count("a"))
print(name.replace("a", "b"))
print(name * 3)